# wrangler.toml
name = "baddbeatz"
compatibility_date = "2024-12-01"
main = "workers-site/index.js"

[[kv_namespaces]]
binding = "RATE_LIMIT"
# Replace the IDs below with your own namespace IDs
id = "61eafb449cdd4ea98a8faba809a5145f"
preview_id = "00000000000000000000000000000000"

[vars]
OPENAI_API_KEY = "your_openai_api_key_here"


[site]
bucket = "./dist"
include = ["**/*.html", "**/*.css", "**/*.js", "**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.ico", "**/*.xml", "**/*.txt", "**/*.json", "**/*.mp3", "**/*.mp4", "**/*.webm", "**/*.pdf"]
exclude = ["node_modules/**", "*.md", "*.py", "tests/**", "__pycache__/**", "scripts/**", "requirements*.txt", ".env*", "temp_venv/**", ".git/**", ".github/**"]

# Provide your OpenAI API key via `wrangler secret put OPENAI_API_KEY`
# or by setting the variable in the Cloudflare dashboard. The value is
# intentionally omitted here so it isn't committed to version control.


[observability.logs]
enabled = true

# Development environment
[env.development]
name = "baddbeatz-dev"
compatibility_date = "2024-12-01"

main = "workers-site/index.js"

[[env.development.kv_namespaces]]
binding = "RATE_LIMIT"
id = "61eafb449cdd4ea98a8faba809a5145f"
preview_id = "00000000000000000000000000000000"


# Production environment
[env.production]
name = "baddbeatz"
compatibility_date = "2024-12-01"
routes = [
  { pattern = "www.baddbeatz.nl", custom_domain = true },
  { pattern = "baddbeatz.nl", custom_domain = true }
]

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT"
id = "61eafb449cdd4ea98a8faba809a5145f"
preview_id = "00000000000000000000000000000000"
