---
name: Workflow Lint &amp; Security Checks

'on':
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Install actionlint (pinned version)
        shell: bash
        run: |
          set -euo pipefail
          curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash \
            | bash -s 1.7.3
          ./actionlint --version

      - name: Run actionlint
        shell: bash
        run: |
          set -euo pipefail
          # Run actionlint against all workflows; disable shellcheck integration to avoid external dependency
          ./actionlint -color -shellcheck=
