---
name: Workflow Lint & Security Checks

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-security:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Install actionlint (pinned)
        shell: bash
        run: |
          set -euo pipefail
          curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash \
            | bash -s 1.7.3
          ./actionlint --version

      - name: Run actionlint
        shell: bash
        run: |
          set -euo pipefail
          ./actionlint -color -shellcheck=

      - name: Set up Python for yamllint
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.12'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint on workflow files
        run: |
          if [ -f ".yamllint" ]; then
            yamllint -c .yamllint .github/workflows
          else
            yamllint .github/workflows
          fi

      - name: Optional hardening checks
        if: ${{ hashFiles('scripts/harden-workflows.sh') != '' }}
        continue-on-error: true
        run: bash scripts/harden-workflows.sh
